# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
random_tensor_A = torch.rand(7, 7)
print(random_tensor_A)
print(random_tensor_A.shape)


tensor([[0.6420, 0.2344, 0.7573, 0.1138, 0.4668, 0.0506, 0.1349],
        [0.1178, 0.8371, 0.3881, 0.7583, 0.2667, 0.8500, 0.1500],
        [0.4344, 0.5596, 0.5041, 0.2568, 0.0063, 0.8358, 0.8484],
        [0.5545, 0.5712, 0.9897, 0.9080, 0.3465, 0.2742, 0.3502],
        [0.7281, 0.0250, 0.1948, 0.2453, 0.1622, 0.9489, 0.9179],
        [0.2783, 0.8909, 0.8444, 0.2129, 0.3779, 0.4394, 0.9334],
        [0.3737, 0.1080, 0.5557, 0.0454, 0.2413, 0.9550, 0.0936]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
random_tensor_B = torch.rand(1, 7)

random_tensor_B_T = random_tensor_B.T

matmul_result = torch.matmul(random_tensor_A, random_tensor_B_T)

print(matmul_result)
print(matmul_result.shape)

tensor([[1.0608],
        [1.2291],
        [1.4383],
        [1.5399],
        [1.4279],
        [1.6777],
        [1.2601]])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
torch.manual_seed(0)

random_tensor_A_redo = torch.rand(7, 7)
random_tensor_B_redo = torch.rand(1, 7)

matmul_result_redo = random_tensor_A_redo @ random_tensor_B_redo.T #

print(matmul_result_redo, matmul_result_redo.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("GPU seed set to 1234")
else:
    print("GPU not available, cannot set GPU seed.")

GPU seed set to 1234



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:


torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")


tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

print((tensor_A, tensor_B))

Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'), tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0'))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
matmul_result_gpu = tensor_A @ tensor_B.T

print(matmul_result_gpu, matmul_result_gpu.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
max_value = matmul_result_gpu.max()
print(f"Max: {max_value}")

min_value = matmul_result_gpu.min()
print(f"Min: {min_value}")

Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
argmax_value = matmul_result_gpu.argmax()
print(f"Argmax: {argmax_value}")

argmin_value = matmul_result_gpu.argmin()
print(f"Argmin: {argmin_value}")


Argmax: 3
Argmin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
torch.manual_seed(7)

tensor_seed_7 = torch.rand(1, 1, 1, 10)

tensor_squeezed = tensor_seed_7.squeeze()

print(tensor_seed_7, tensor_seed_7.shape)

print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
